### ISSUE TITLE
Consider detaching fork

### ISSUE THREAD

**Issue by shamil** [criteo/py-consul#66]
Hi,

Thanks for continuing the development of original `consul` client. 

This is not an issue, just a suggestion. Since there was lots of refactoring lately and the project far more progressed, and it's maintained, maybe it worth detaching the fork from upstream. 

If intereseted, here is the link for that : https://support.github.com/request/fork

Thanks

**Comment by mbrulatout** [comment]
Hi,

Thanks for the suggestion! I'll bring this up with my team, but indeed that would make sense.
This would probably also require a move to https://github.com/criteo as this wouldn't be a fork (in criteo-forks) anymore.
We'll keep you posted

**Comment by mbrulatout** [comment]
Hi @shamil, this "issue" is now resolved. 
As mentioned above, we moved to https://github.com/criteo too.

Thanks for the suggestion
