### ISSUE TITLE
Notification: Linking to criteo/py-consul as recommended fork

### ISSUE THREAD

**Issue by cablehead** [criteo/py-consul#69]
Hi there,

I wanted to let you know that I have updated the [python-consul/python-consul](https://github.com/python-consul/python-consul) README to direct users to criteo/py-consul as the recommended fork for ongoing maintenance and support.

A special thanks to @asteven for encouraging me to clarify the status and ensure the community has the best resources moving forward. Additionally, thank you to the criteo team for taking over the project and continuing its development.

Once you've read this, feel free to close the issue.

best 💚🙏🏻

**Comment by mbrulatout** [comment]
Thanks @cablehead :)
